name: Add Issue to Project when assigned
on:
  issues:
    types: [assigned]
jobs:
  job:
    # This job runs when a user is assigned to an Issue.
    #
    # We grab the assignee's username from the event payload, loop
    # over all user:column pairs and create a card in the relevant
    # column if the username is matched.
    #
    # The environment variable name must start with 'GS_', but the
    # remainder isn't important. For the sake of convention, use
    # 'GS_' + your Github username.
    #
    # The environment variable value must be your Github username
    # and the ID of the column you wish to add the cards to. These
    # must be separated by a comma.
    #
    # To find a Column ID, press the three dots on a column, and
    # select 'Copy column link'. The Column ID can be found in this
    # URL.
    # e.g: https://github.com/orgs/giantswarm/projects/30#column-1527540
    # has a column ID of 1527540.
    name: Add issue to project when assigned
    runs-on: ubuntu-latest
    steps:
    - name: Create project card for issue in appropriate column
      env:
        GS_CHRISTIANBIANCHI: whites11,8708894
        GS_GLITCHCRAB: glitchcrab,5976311
        GS_JOSEPHSALISBURY: JosephSalisbury,7851590
        GS_OMEGAS27: omegas27,7980947
        GS_TEEMOW: teemow,10823295
        GS_PUJA108: puja108,10823295
        GS_OSHRATN: Oshratn,10823295
        GS_PIPO02MIX: pipo02mix,8709058
        GS_PIPO02MIX_HORIZON: pipo02mix,10823295
        GS_MIRCOHELLE: Mircohelle,6017595
        GS_JAKUBSOBON: wtty-fool,8314491
        GS_UBERGESUNDHEIT: ubergesundheit,7606262
        GS_DRANNAVD: DrAnnavd,8518324
        GS_CED0PS: ced0ps,8347672
        GS_AVERAGEMARCUS: AverageMarcus,15956421
        GS_LOLLONES: LolloneS,17508743
      run: |
        event_assignee=$(cat $GITHUB_EVENT_PATH | jq -r .assignee.login)
        for envvar in $(env | grep GS_ | awk -F '=' '{print $2}'); do
            assignee=$(echo $envvar | awk -F ',' '{print $1}')
            column_id=$(echo $envvar | awk -F ',' '{print $2}')

            if [[ "$assignee" == "$event_assignee" ]]; then
                curl https://api.github.com/projects/columns/$column_id/cards \
                    --header 'authorization: Bearer ${{ secrets.ASSIGN_TO_PROJECT_TOKEN }}' \
                    --header 'Accept: application/vnd.github.inertia-preview+json' \
                    --data "{\"content_id\": $(cat $GITHUB_EVENT_PATH | jq .issue.id), \"content_type\": \"Issue\"}"
            fi
        done
